name: api-docs
on: pull_request

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy api-docs
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          ./github-actions/api-docs.sh
