name: deploy-api-docs
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: api-docs.vapor.codes
    runs-on: ubuntu-latest
    steps:
    - name: Deploy api-docs
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          ./github-actions/api-docs.sh
